use std::path::{Path, PathBuf};

use rusqlite::Connection;
use serde::Serialize;

struct ExportRow {
    title: String,
    content: String,
    node_type: String,
    vault_code: Option<String>,
    slug: String,
    export_policy: String,
    created_at: String,
    updated_at: String,
}

#[derive(Debug, Serialize)]
pub struct ExportResult {
    pub exported: usize,
    pub excluded: usize,
    pub redacted: usize,
    pub output_dir: String,
}

fn escape_yaml_scalar(s: &str) -> String {
    if s.contains(':') || s.contains('#') || s.contains('"') || s.contains('\n') {
        format!("{:?}", s) // double-quoted YAML scalar; Rust's Debug-escaping matches YAML's own well enough for titles
    } else {
        s.to_string()
    }
}

fn relative_path_for(row: &ExportRow) -> PathBuf {
    let stem = match &row.vault_code {
        // preserves human-readable IDs like "Wiki/[WK04]-kai.md" through
        // migration — never an opaque UUID filename
        Some(code) => format!("[{code}]-{}", row.slug),
        None => row.slug.clone(),
    };
    // node_type doubles as the exported folder, mirroring the UI's virtual
    // folders — still nothing on disk inside the app itself groups by folder
    PathBuf::from(&row.node_type).join(format!("{stem}.md"))
}

fn render_markdown(row: &ExportRow) -> String {
    let content = if row.export_policy == "redact" {
        "*(content redacted by export_policy)*".to_string()
    } else {
        row.content.clone()
    };
    format!(
        "---\ntitle: {title}\nnode_type: {node_type}\nsource: sqlite-export\nreadonly: true\ncreated_at: {created_at}\nupdated_at: {updated_at}\n---\n\n<!-- Generated by noteapp's markdown export — edits here are never read back. Edit in the app instead. -->\n\n{content}\n",
        title = escape_yaml_scalar(&row.title),
        node_type = row.node_type,
        created_at = row.created_at,
        updated_at = row.updated_at,
        content = content,
    )
}

/// One-way, atomic markdown export. Writes into a fresh temp directory, then
/// swaps it into place — `fs::rename` can't atomically replace an existing
/// non-empty directory on Windows the way POSIX rename can, so the previous
/// export is moved aside first and removed only after the new one is
/// successfully in place, keeping the window where data could be lost as
/// small as possible without depending on POSIX-only semantics.
pub fn export_vault(conn: &Connection, output_dir: &Path) -> rusqlite::Result<ExportResult> {
    let mut stmt = conn.prepare(
        "SELECT title, content, node_type, vault_code, slug, export_policy, created_at, updated_at
         FROM nodes WHERE deleted_at IS NULL",
    )?;
    let rows: Vec<ExportRow> = stmt
        .query_map([], |r| {
            Ok(ExportRow {
                title: r.get(0)?,
                content: r.get(1)?,
                node_type: r.get(2)?,
                vault_code: r.get(3)?,
                slug: r.get(4)?,
                export_policy: r.get(5)?,
                created_at: r.get(6)?,
                updated_at: r.get(7)?,
            })
        })?
        .collect::<Result<_, _>>()?;
    drop(stmt);

    let parent = output_dir.parent().expect("export dir must have a parent");
    let dir_name = output_dir.file_name().expect("export dir must have a name").to_string_lossy();
    let tmp_dir = parent.join(format!("{dir_name}.tmp"));
    let old_dir = parent.join(format!("{dir_name}.previous"));

    if tmp_dir.exists() {
        std::fs::remove_dir_all(&tmp_dir).expect("failed to clear stale export temp dir");
    }
    std::fs::create_dir_all(&tmp_dir).expect("failed to create export temp dir");

    let mut exported = 0;
    let mut excluded = 0;
    let mut redacted = 0;
    for row in &rows {
        if row.export_policy == "exclude" {
            excluded += 1;
            continue;
        }
        if row.export_policy == "redact" {
            redacted += 1;
        }
        let full_path = tmp_dir.join(relative_path_for(row));
        std::fs::create_dir_all(full_path.parent().unwrap()).expect("failed to create export subdirectory");
        std::fs::write(&full_path, render_markdown(row)).expect("failed to write exported note");
        exported += 1;
    }

    if old_dir.exists() {
        std::fs::remove_dir_all(&old_dir).ok();
    }
    if output_dir.exists() {
        std::fs::rename(output_dir, &old_dir).expect("failed to move previous export aside");
    }
    std::fs::rename(&tmp_dir, output_dir).expect("failed to finalize export");
    if old_dir.exists() {
        std::fs::remove_dir_all(&old_dir).ok();
    }

    Ok(ExportResult {
        exported,
        excluded,
        redacted,
        output_dir: output_dir.display().to_string(),
    })
}
